#server:
#  port: 8080
#girl:
#  cpuSize: B 
#  age: 18
##content: "cupSize: ${cpuSize}, age: ${age}"


spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/sqlstudy
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
   